### ISSUE TITLE
Is @CheckResult used? And if not, why?

### ISSUE THREAD

**Issue by Rainer-Lang** [gabrielittner/auto-value-with#16]

**Comment by Rainer-Lang** [comment]
Should I annotate the abstract method?

**Comment by gabrielittner** [comment]
That is completely up to your preference. The extension will copy all annotations of the abstract method and will add them to the implementation. So if you like using `@CheckResult`  you can do so.

**Comment by Rainer-Lang** [comment]
@gabrielittner Thanks - and thanks for this extension. :+1:
