### ISSUE TITLE
Add support for generic arguments

### ISSUE THREAD

**Issue by esneider** [gabrielittner/auto-value-with#24]
I don't know how much work is needed to implement this feature, but it'd be great to be able to do something like this:

```java
public abstract class PersistentModel<T extends PersistentModel<T>> {
    public abstract long id();
    public abstract T withId(long id);
}

@AutoValue
public abstract class MyModel extends PersistentModel<MyModel> {}
```

Which currently throws:

> Error:(6, 17) error: @AutoValue processor threw an exception: java.lang.IllegalArgumentException: withId() in [...].MyModel returns T, expected [...].MyModel

**Comment by gabrielittner** [comment]
I'm looking into it.

As a temporary workaround you could override the with methods in `MyModel` with the concret type:
```java
@AutoValue
public abstract class MyModel extends PersistentModel<MyModel> {
   @Override public abstract MyModel withId(long id);
}
```
