### ISSUE TITLE
Adding with-er methods generates a lot of warnings

### ISSUE THREAD

**Issue by dimsuz** [gabrielittner/auto-value-with#25]
While using this extension and adding a lot of `with`-methods I also start to see a lot of warnings during compilation, for example:

```
warning: @AutoValue classes cannot have abstract methods other than property getters and Builder converters
  public abstract Flight withIsInternational(boolean isInternational);
                         ^
```

Isn't there something in AutoValue extension API which can help to suppress such warnings, because obviously in this case we want these methods?...

**Comment by gabrielittner** [comment]
It will be fixed in AutoValue 1.3
