### ISSUE TITLE
@Override annotation is duplicated

### ISSUE THREAD

**Issue by Maragues** [gabrielittner/auto-value-with#26]
Due to https://github.com/gabrielittner/auto-value-with/issues/24, I was forced to add a non-generics implementation such as the following 

```
  @NonNull
  @Override
  public abstract Timeline withUploadStatus(@NonNull UPLOAD_STATUS status);
```

*auto-value-with* generates the withUploadStatus method with a duplicated @Override annotation, which of course throws a *duplicate annotation* compile time error

```
  @Override
  @NonNull
  @Override
  public final Timeline withUploadStatus(ISynchronizable.UPLOAD_STATUS uploadStatus) {
    return new AutoValue_Timeline(id(), ..., uploadStatus, ...);
  }
```

Removing the @Override annotation fixes the issue.

**Comment by gabrielittner** [comment]
I think it will work when you remove @Override from your overridden method.
I'm on mobile right now but will take a look later today

**Comment by Maragues** [comment]
Yes, that fixes the issue, I just wanted to let you know.

Thanks!
