### ISSUE TITLE
Multiple Fields Support

### ISSUE THREAD

**Issue by Maradox** [gabrielittner/auto-value-with#35]
Are there plans to support multiple fields? For example: `withEmailAndPhone`.
I know it's currently possible by having `withEmail`and `withPhone`, but this causes one unnecessary object creation.

**Comment by gabrielittner** [comment]
I've already got a prototype for this locally, will try to finish it this weekend.

**Comment by Maradox** [comment]
Thats great, thanks.

**Comment by gabrielittner** [comment]
It's now available in the `0.2.0-SNAPSHOT`, let me know if you have any issues.
