### ISSUE TITLE
Cut final release since AutoValue 1.3 is released

### ISSUE THREAD

**Issue by vanniktech** [gabrielittner/auto-value-with#39]
Do you plan on cutting a release since AutoValue 1.3 is finally released?

**Comment by gabrielittner** [comment]
Yes, planned for today

**Comment by gabrielittner** [comment]
It's out https://repo1.maven.org/maven2/com/gabrielittner/auto/value/auto-value-with/1.0.0/

**Comment by vanniktech** [comment]
Thank you :)
