### ISSUE TITLE
IllegalStateException: Missing required properties

### ISSUE THREAD

**Issue by codeteo** [gabrielittner/auto-value-with#47]
so I'm trying your extension with AutoValue and I'm getting  : 

         java.lang.IllegalStateException: Missing required properties: accountId name company postId flaggedYes totalComments

The class is : 

```
@AutoValue
public abstract class FeedItem implements Parcelable {
    public abstract String getAccountId();
    public abstract String getName();
    public abstract String getCompany();
    @Nullable
    public abstract String getAvatar();
    @Nullable
    public abstract String getPostImage();
    @Nullable
    public abstract String getThumb();
    public abstract String getPostId();
    public abstract String getFlaggedYes();
    public abstract int getTotalFlags();
    public abstract int getTotalComments();

    // Returns slightly altered instance
    public FeedItem withTotalFlags(int totalFlags) {
        return builder().setTotalFlags(totalFlags).build();
    }

    public static Builder builder() {
        return new AutoValue_FeedItem.Builder();
    }

    @AutoValue.Builder
    public static abstract class Builder {
        public abstract Builder setAccountId(String accountId);
        public abstract Builder setName(String name);
        public abstract Builder setCompany(String company);
        public abstract Builder setAvatar(@Nullable String avatar);
        public abstract Builder setPostImage(@Nullable String image);
        public abstract Builder setThumb(@Nullable String thumb);
        public abstract Builder setPostId(String postId);
        public abstract Builder setFlaggedYes(String flaggedYes);
        public abstract Builder setTotalFlags(int totalFlags);
        public abstract Builder setTotalComments(int totalComments);

        public abstract FeedItem build();
    }

} 
```

And I'm using it like : 

            FeedItem feedItem = dataset.get(position)
                .withTotalFlags(updatedTotalFlags);

Am I using it wrong? Thanks and Happy new year!!

PS : would be great if you could add a demo/sample

**Comment by gabrielittner** [comment]
To use auto-value-with the with method needs to be abstract. So your class would have to look like this

```java
@AutoValue
public abstract class FeedItem implements Parcelable {
    // properties

    // will be implemented by auto-value-with
    public abstract FeedItem withTotalFlags(int totalFlags);

   @AutoValue.Builder
    public static abstract class Builder {
         // ...
    } 
}
```

Your current implementation throws an exception because you create an empty builder and only set `totalFlags`. If you want to go through a builder and not use auto-value-with do this:

```java
@AutoValue
public abstract class FeedItem implements Parcelable {
    // properties

    // auto-value will implement this method for you and return a Builder instance populated with the values of this FeedItem
    public abstract Builder toBuilder();

    // Returns slightly altered instance
    public FeedItem withTotalFlags(int totalFlags) {
        return toBuilder().setTotalFlags(totalFlags).build();
    }

    public abstract FeedItem withTotalFlags(int totalFlags);

    // builder
} 
```

Both approaches have their own advantages. The first one using auto-value-with will not create a builder instance so you save an allocation. Going through the builder might be better if you do any data validation there.

**Comment by gabrielittner** [comment]
Here is a sample for multiple auto value extensions: https://github.com/gabrielittner/auto-value-playground

**Comment by maheswaranecemohan** [comment]
Hi ,
I am facing the same issue. Below is my code.

@AutoValue
public abstract class PaymentHistoryViewModelNew implements Parcelable {

    public abstract String paidAmount();

    public abstract String numberOfPayments();

    public abstract List<PaymentItemViewModelNew> paymentViewModels();


    public static Builder builder() {
        return new AutoValue_PaymentHistoryViewModelNew.Builder();
    }

    public static PaymentHistoryViewModelNew from(PaymentHistoryResponse paymentHistoryResponse, String paidAmount) {
        List<PaymentItemViewModelNew> list = new ArrayList<>();

        if (paymentHistoryResponse.payments != null) {
            Collections.sort(paymentHistoryResponse.payments, new Comparator<Payment>() {
                @Override
                public int compare(Payment thisPayment, Payment otherPayment) {
                    Date thisPaymentDate = DateHelper.parseDate(thisPayment.date, DateHelper.DATE_API_FORMAT);
                    Date otherPaymentDate = DateHelper.parseDate(otherPayment.date, DateHelper.DATE_API_FORMAT);
                    if (thisPaymentDate != null && otherPaymentDate != null) {
                        return otherPaymentDate.compareTo(thisPaymentDate);
                    }
                    return 0;
                }
            });

            for (Payment payment : paymentHistoryResponse.payments) {
                list.add(PaymentItemViewModelNew.builder().build().from(payment));
            }
        }

        return builder()
                .numberOfPayments(NumberUtils.formatTimes(list.size()))
                .paidAmount(paidAmount)
                .paymentViewModels(list)
                .build();
    }

    @AutoValue.Builder
    public abstract static class Builder {
        public abstract Builder paidAmount(String amount);

        public abstract Builder numberOfPayments(String amount);

        public abstract Builder paymentViewModels(List<PaymentItemViewModelNew> list);

        public abstract PaymentHistoryViewModelNew build();
    }
}
