### ISSUE TITLE
Binaries of latest release (1.1.0) lack class files of shaded dependencies

### ISSUE THREAD

**Issue by sesamzoo** [gabrielittner/auto-value-with#96]
First of all: Thanks a lot for this extension.

**The issue:** 
When upgrading from version 1.1.0-rc1 to version 1.1.0 the following error occurs:
> Execution failed for task ':compileJava'.
> \> java.lang.NoClassDefFoundError: com/gabrielittner/auto/value/util/AutoValueUtil

The published [auto-value-with-1.1.0.jar](https://repo1.maven.org/maven2/com/gabrielittner/auto/value/auto-value-with/1.1.0/auto-value-with-1.1.0.jar) file contains only two .class files (for `AutoValueWithExtension`and `WithMethod`). The .class files that are [relocated by the shadowJar task](https://github.com/gabrielittner/auto-value-with/blob/master/auto-value-with/build.gradle#L20-L21) are not contained anymore.

This can be reproduced when publishing to the local maven repository by running the `installArchives` task.

**Comment by TonyTangAndroid** [comment]
I can confirm that 1.1.0-rc1 works fine but 1.1.0 breaks with the same error.

**Comment by gabrielittner** [comment]
Released 1.1.1 to fix the issue

**Comment by sesamzoo** [comment]
Thanks a lot, @gabrielittner .
